--Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

--1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

--By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

fibs :: [Int]
fibs = 0 : 1 : [ a + b | (a, b) <- zip fibs (tail fibs)]

--make me a list comprehension later
even' :: Int -> Int
even' n 
  | mod n 2 == 0 = 0
  | otherwise    = n

--UGLY
getN n = if last (take n fibs) > 4000000 then (n-1) else getN (n+1) 

showSum = sum $ take (getN 1) $ map (\ x -> even' x) fibs 
